package com.kishorThirdApp;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "taskManager")
public class TaskInfo {
    private String id;
    private String title;
    private String description;
    private String status;
    private String assignee;
    private String imageUrl;
    private String resizedImage;

    public TaskInfo(){}

    public TaskInfo(String title, String description, String status, String assignee){
        this.title = title;
        this.description = description;
        this.status = status;
        this.assignee = assignee;

    }
    public TaskInfo(String title, String description,  String assignee){
        this.title = title;
        this.description = description;
        this.assignee = assignee;
        this.status ="Assigned";

    }
    public TaskInfo(String title, String description){
        this.title = title;
        this.description = description;
        this.status="available";

    }


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }


    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
    @DynamoDBAttribute
    public String getAssignee() {
        return assignee;
    }

    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    @DynamoDBAttribute
    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getResizedImage() {
        return resizedImage;
    }

    public void setResizedImage(String resizedImage) {
        this.resizedImage = resizedImage;
    }
}
